config/routes.rb
Rails.application.routes.draw do
  #/login 'session#new'
  #/logout 'session#destroy'
  root 'pages#home'

  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :owners, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :restaurants, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :reservations, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    resources :reservations, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :restaurants do
    resources :reservations, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :restaurants do
    resources :reviews, only: [:create, :show, :destroy, :edit]
  end

  resources :users do
    resources :reviews, only: [:create, :show, :destroy]
  end

  resources :owners do
    resources :restaurants, only: [:new, :create, :show, :edit, :destroy]
  end

  resources :reservations do
    resources :restaurants, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/owner.rb
class Owner < ApplicationRecord
#  attr_accessor :id, :email, :name, :phone

  has_secure_password

  has_many :restaurants

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      redirect_to "/owners/#{:id}", notice: "You are now signed up to Seat Your Self!"
    else
      render :new
    end
  end

  def edit
    @owner = Owner.find(params[:id])
  end

  def show
    @owner = Owner.find(params[:id])
  end

  def update
    @owner = Owner.find(params[:id])

    if @owner.update_attributes(owner_params)
      redirect_to owner_url(@owner)
    else
      render :edit
    end
  end

private
  def owner_params
    params.require(:owner).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/owner_helper.rb
module OwnerHelper
end

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this </h2>

      <ul>
      <% @owner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
    <% end %>

app/views/owners/destroy.html.erb
<h1>Owner#destroy</h1>
<p>Find me in app/views/owner/destroy.html.erb</p>

app/views/owners/edit.html.erb
<h1>Owner#edit</h1>
<p>Find me in app/views/owner/edit.html.erb</p>

app/views/owners/new.html.erb
<h1>Register for owner account</h1>

    <%= render 'form' %>

    <%= link_to 'Cancel', restaurants_path %>

    


</body>

app/views/owners/show.html.erb
<h1>Welcome<%= @owner %>!</h1>
<p><%= link_to "Home", restaurants_path %></p>
<p><%= link_to "Edit Your Profile", "/owners/#{:owner_id}/edit" %></p>
<p><%= link_to "Edit Your Restaurants", "owners/#{:owner_id}/restaurants/#{:id}/edit" %></p>


<h3>Owned Restaurants</h3>
<% @restaurants.each do |restaurant| %>
  <div class="table">
    <h3><%= link_to restaurant.name, restaurant_path(restaurant)%></h3>
    <%= "Resevations for tonight :" %>
    <% @reservations.each do |reservation| %>
     reservation = Reservation.show(@ownder_id)
     <% end %>
  </div>
<% end %>


<% if current_user %>
<% end %>
</body>
</html>

app/views/owners/update.html.erb
<h1>Owner#update</h1>
<p>Find me in app/views/owner/update.html.erb</p>