config/routes.rb
Rails.application.routes.draw do
  #/login 'session#new'
  #/logout 'session#destroy'
  root 'pages#home'

  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :owners, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :restaurants, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :reservations, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    resources :reservations, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :restaurants do
    resources :reservations, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :restaurants do
    resources :reviews, only: [:create, :show, :destroy, :edit]
  end

  resources :users do
    resources :reviews, only: [:create, :show, :destroy]
  end

  resources :owners do
    resources :restaurants, only: [:new, :create, :show, :edit, :destroy]
  end

  resources :reservations do
    resources :restaurants, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owner.rb
class Owner < ApplicationRecord
#  attr_accessor :id, :email, :name, :phone

  has_secure_password

  has_many :restaurants

end

app/models/reservation.rb
class Reservation < ApplicationRecord
#  attr_accessor :user_id, :restaurant_id, :size, :when
  validates :size, :when, presence: true

  belongs_to :user
  belongs_to :restaurant

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
#  attr_accessor :id, :name, :owner_id, :capacity, :location, :phone, :food_type, :description

  has_many :reservations
  has_many :users, through: :reservations
  has_many :reviews
  has_many :users, through: :reviews

  belongs_to :owner

  def self.search(search)
    where("name ILIKE ? OR food_type ILIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/models/review.rb
class Review < ApplicationRecord
#  attr_accessor :user_id, :restaurant_id, :id, :content
  validates :content, presence: true

  belongs_to :user
  belongs_to :restaurant

end

app/models/user.rb
class User < ApplicationRecord
#  attr_accessor :id, :name, :email, :phone
  validates :name, :email, :phone, presence: true

  has_secure_password

  has_many :reviews
  has_many :reservations
  has_many :restaurants, through: :reservations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_url
    end
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      redirect_to "/owners/#{:id}", notice: "You are now signed up to Seat Your Self!"
    else
      render :new
    end
  end

  def edit
    @owner = Owner.find(params[:id])
  end

  def show
    @owner = Owner.find(params[:id])
  end

  def update
    @owner = Owner.find(params[:id])

    if @owner.update_attributes(owner_params)
      redirect_to owner_url(@owner)
    else
      render :edit
    end
  end

private
  def owner_params
    params.require(:owner).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_restaurant
  before_action :ensure_logged_in, only: [:create, :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      redirect_to restaurant_url(@restaurant), notice: 'Review created successfully'
    else
      render 'restaurants/show'
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
    @review = Review.find(params[:id])
    @review.delete
    redirect_to restaurant_url
  end

private
  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:user_id, :restaurant_id, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  #def create
#    @user = User.find_by(:email => params[:email])
  #  if @user.authernticate(params[:password]
  #    session[:user_id]) = @user.#  redirect_to root_url
# end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url(@user), notice: "Signed up!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_url
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to restaurants_url
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :phone, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owner_helper.rb
module OwnerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

    <title>Seat Yourself</title>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>
    <header>
      <% if current_user %>
        <div id="alert">Signed in as <%= current_user.email %>.</div>
        <div class="btn btn-alt"><%= link_to "Log out", session_path("current"), :method => :delete %></div>
      <% else %>
        <div class="btn btn-alt"><%= link_to "Sign up", new_user_path %></div><div class="btn btn-alt"><%= link_to "Log in", new_session_path %></div>
      <% end %>

      <% if current_user %>
      <div class="btn btn-alt"><%= link_to "Profile", "/users/#{session[:user_id]}" %></div>
      <% end %>
      <a class = "nav_item" href='/restaurants'>Restaurants</a>


      <div class="logo_style">
      <a href="/"><%= image_tag "seatyourself.png", :class => "logo" %></a>
      </div>


      <div class="white_bar"></div>

    </header>
    <%= yield %>
    <footer>
      <div class="open_space"></div>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<h3 class="search_greeting"> Search by Food Type or Name</h3>
<p class="sub_search_greeting">Easy search feature allows you to narrow down your choice</p>

<div class="search_bar">
  <%= form_tag(restaurants_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "What would you like?", required: true %>
  <%= submit_tag "Search" %>
  <% end %>
</div>